---
- name: Install plasma-nm
  ansible.builtin.package:
    name: plasma-nm
    state: present
  become: true
- name: Install bluedevil
  ansible.builtin.package:
    name: bluedevil
    state: present
  become: true
- name: Install gnome-keyring
  ansible.builtin.package:
    name: gnome-keyring
    state: present
  become: true
- name: Install polkit-kde-agent
  ansible.builtin.package:
    name: polkit-kde-agent
    state: present
  become: true
- name: Install dolphin
  ansible.builtin.package:
    name: dolphin
    state: present
  become: true
- name: Install systemsettings
  ansible.builtin.package:
    name: systemsettings
    state: present
  become: true
- name: Install Kate
  ansible.builtin.package:
    name: kate
    state: present
  become: true