---
- name: restart paccache
  ansible.builtin.service:
    name: paccache.timer
    state: restarted
  become: true

- name: stop systemd per-user instance
  ansible.builtin.service:
    name: "user@{{ user.uid }}"
    state: stopped
  become: true
