---
- name: Install pipenv
  become: true
  ansible.builtin.package:
    name: python-pipenv
    state: present

- name: Install pipx
  become: true
  ansible.builtin.package:
    name: python-pipx
    state: present

- name: Install black
  become: true
  ansible.builtin.package:
    name: python-black
    state: present

- name: Install documentation
  become: true
  ansible.builtin.package:
    name: python-docs
    state: present

- name: Install python utils
  become: true
  ansible.builtin.package:
    name:
      - clang
      - uv
      - gtk4
      - libadwaita
      - libsoup3
      - libportal-gtk4
      - gobject-introspection
      - sassc
      - python-opencv
    state: present
