- name: Install i3
  become: true
  ansible.builtin.package:
    name:
      - i3-wm
      - i3blocks
      - i3status
    state: present

- name: Install py3status
  become: true
  ansible.builtin.package:
    name:
      - py3status
    state: present
