---
- name: Install rofi
  become: true
  ansible.builtin.package:
    name:
      - rofi
    state: present
  tags:
    - rofi

- name: Install i3-wm for rofi window switching
  become: true
  ansible.builtin.package:
    name:
      - i3-wm
    state: present
  tags:
    - rofi

