---
- name: Install GNOME
  become: true
  ansible.builtin.package:
    name:
      - gnome-extra
      - gnome-tweaks
      - xorg-server-xwayland
    state: present

- ansible.builtin.include_tasks: dconf.yml
- ansible.builtin.include_tasks: gtk.yml
- ansible.builtin.include_tasks: online_accounts.yml
