---
- name: Install yazi
  ansible.builtin.package:
    name: yazi
    state: present
  become: true

- name: Install ffmpegthumbnailer
  ansible.builtin.package:
    name: ffmpegthumbnailer
    state: present
  become: true
