---
- name: update cursor theme cache
  ansible.builtin.command: gtk-update-icon-cache {{ cursor_theme.install_path | default('/usr/share/icons') }}/{{ cursor_theme.variant }}
  become: true
  ignore_errors: true
  listen: "update cursor theme cache"

- name: reload cursor theme
  ansible.builtin.command: xrdb -merge ~/.Xresources
  ignore_errors: true
  listen: "update cursor theme cache"
